plugins {
	id "se.bjurr.gradle.bundle-jar"
}

dependencies {
	api "com.github.jknack:handlebars:4.5.5"
	implementation "com.jayway.jsonpath:json-path:3.0.0"
	implementation "org.eclipse.jgit:org.eclipse.jgit:7.8.0.202609011348-r"
	implementation "tools.jackson.core:jackson-databind:3.2.2"

	testImplementation "org.slf4j:slf4j-simple:2.0.19"
	testImplementation "org.junit.jupiter:junit-jupiter:6.1.3"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher:6.1.3"
	testImplementation "org.assertj:assertj-core:3.27.7"
	testImplementation "org.wiremock:wiremock-standalone:3.13.2"
	testImplementation "org.openjdk.nashorn:nashorn-core:15.7"
}

test {
	useJUnitPlatform()
}

javaExtension {
	javaVersion = 17
}
