plugins {
	id "se.bjurr.gradle.bundle-jar"
}

repositories {
	mavenCentral()
}

dependencies {
	api "com.github.jknack:handlebars:4.5.4"

	implementation 'com.squareup.retrofit2:retrofit:3.0.0'
	// okio is transitive from retrofit: https://github.com/square/retrofit/issues/4210
	implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
	implementation "com.jayway.jsonpath:json-path:3.0.0"
	implementation 'net.minidev:json-smart:2.6.0' // json-path transitive
	implementation "org.eclipse.jgit:org.eclipse.jgit:7.8.0.202609011348-r"
	implementation 'org.gitlab:java-gitlab-api:4.1.1'
	implementation "commons-io:commons-io:2.22.0" // java-gitlab-api transitive
	implementation "com.fasterxml.jackson.core:jackson-core:2.22.2"
	implementation "com.fasterxml.jackson.core:jackson-databind:2.22.2"
	implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.22.2"

	testImplementation "org.slf4j:slf4j-simple:2.0.19"
	testImplementation "org.junit.jupiter:junit-jupiter:6.1.3"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher:6.1.3"
	testImplementation "org.assertj:assertj-core:3.27.7"
	testImplementation "com.approvaltests:approvaltests:31.0.0"
	testImplementation "org.mockito:mockito-core:5.23.0"
	testImplementation "org.wiremock:wiremock-standalone:3.13.2"
}

test {
	useJUnitPlatform()
}

javaExtension {
	javaVersion = 17
}